# Generated by Django 5.2.9 on 2025-12-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=500)),
                ('autorite', models.CharField(blank=True, max_length=255, null=True)),
                ('type_publication', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='marches_app.marche')),
            ],
        ),
    ]
