# Generated by Django 5.2.9 on 2026-02-09 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=500)),
                ('autorite', models.CharField(blank=True, max_length=255, null=True)),
                ('type_publication', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(blank=True, max_length=255, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('montant', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='marches_app.marche')),
            ],
        ),
        migrations.CreateModel(
            name='AvisAttributionDefinitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.TextField(blank=True, null=True)),
                ('reference_publication', models.CharField(blank=True, max_length=255, null=True)),
                ('type_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('lot', models.CharField(blank=True, max_length=100, null=True)),
                ('financement', models.CharField(blank=True, max_length=255, null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('type_date_publication', models.CharField(blank=True, max_length=100, null=True)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
                ('date_attribution', models.DateField(blank=True, null=True)),
                ('attributaire', models.TextField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('boite_postale', models.CharField(blank=True, max_length=50, null=True)),
                ('telephones', models.CharField(blank=True, help_text='Numéros séparés par virgule', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nif', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_lettres', models.TextField(blank=True, null=True)),
                ('montant_chiffres', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('devise', models.CharField(blank=True, max_length=20, null=True)),
                ('ttc', models.BooleanField(blank=True, null=True)),
                ('format_detecte', models.CharField(default='ATTRIBUTION_DEFINITIVE', max_length=50)),
                ('qualite_ocr', models.CharField(blank=True, max_length=30, null=True)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marche', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis_attribution', to='marches_app.marche')),
            ],
        ),
        migrations.CreateModel(
            name='PpmMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_ppm', models.CharField(max_length=100)),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('autorite', models.TextField(blank=True, null=True)),
                ('abreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_activites', models.IntegerField(blank=True, null=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('statut_ppm', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_revisions', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('numero_activite', models.IntegerField()),
                ('realisation', models.TextField(blank=True, null=True)),
                ('source_financement', models.CharField(blank=True, max_length=100, null=True)),
                ('type_marche', models.CharField(blank=True, max_length=50, null=True)),
                ('mode_selection', models.CharField(blank=True, max_length=50, null=True)),
                ('date_lancement', models.DateTimeField(blank=True, null=True)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('date_demarrage', models.DateTimeField(blank=True, null=True)),
                ('date_achevement', models.DateTimeField(blank=True, null=True)),
                ('statut_activite', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ppm_marche',
                'ordering': ['reference_ppm', 'numero_activite'],
                'unique_together': {('reference_ppm', 'numero_activite')},
            },
        ),
    ]
