# Generated by Django 5.2.9 on 2026-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avisattributiondefinitive',
            old_name='date_limite',
            new_name='date_limite_depot',
        ),
        migrations.RenameField(
            model_name='avisattributiondefinitive',
            old_name='adresse',
            new_name='intitule_marche',
        ),
        migrations.RenameField(
            model_name='avisattributiondefinitive',
            old_name='intitule',
            new_name='lot_concerne',
        ),
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='boite_postale',
        ),
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='date_attribution',
        ),
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='email',
        ),
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='qualite_ocr',
        ),
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='type_date_publication',
        ),
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='type_reference',
        ),
        migrations.AddField(
            model_name='avisattributiondefinitive',
            name='date_ouverture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avisattributiondefinitive',
            name='nombre_offres_recus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='avisattributiondefinitive',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisattributiondefinitive',
            name='devise',
            field=models.CharField(blank=True, default='MRU', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='avisattributiondefinitive',
            name='nif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avisattributiondefinitive',
            name='ttc',
            field=models.BooleanField(default=True),
        ),
    ]
