# Generated by Django 5.2.9 on 2025-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
