# Generated by Django 5.2.9 on 2025-12-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches_app', '0002_document_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PpmMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_ppm', models.CharField(max_length=100)),
                ('annee', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('autorite', models.TextField(blank=True, null=True)),
                ('abreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_activites', models.IntegerField(blank=True, null=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('statut_ppm', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_revisions', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('numero_activite', models.IntegerField()),
                ('realisation', models.TextField(blank=True, null=True)),
                ('source_financement', models.CharField(blank=True, max_length=100, null=True)),
                ('type_marche', models.CharField(blank=True, max_length=50, null=True)),
                ('mode_selection', models.CharField(blank=True, max_length=50, null=True)),
                ('date_lancement', models.DateTimeField(blank=True, null=True)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('date_demarrage', models.DateTimeField(blank=True, null=True)),
                ('date_achevement', models.DateTimeField(blank=True, null=True)),
                ('statut_activite', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ppm_marche',
                'ordering': ['reference_ppm', 'numero_activite'],
                'unique_together': {('reference_ppm', 'numero_activite')},
            },
        ),
    ]
