# Generated by Django 5.2.9 on 2026-02-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marches_app', '0002_rename_date_limite_avisattributiondefinitive_date_limite_depot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='avisattributiondefinitive',
            name='ttc',
        ),
    ]
