# Generated by Django 5.2.9 on 2026-02-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches_app', '0003_remove_avisattributiondefinitive_devise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('nif', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marche',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_source', models.CharField(max_length=255)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('devise', models.CharField(default='MRU', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attributaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='marches_app.attributaire')),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='marches_app.marche')),
            ],
            options={
                'unique_together': {('marche', 'attributaire', 'fichier_source')},
            },
        ),
        migrations.DeleteModel(
            name='AvisAttributionDefinitive',
        ),
    ]
