# Generated by Django 5.2.9 on 2026-03-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches_app', '0004_attributaire_remove_marche_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marche',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marche',
            name='montant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marche',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
