# Generated by Django 5.2.9 on 2026-03-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches_app', '0005_marche_date_debut_marche_date_fin_marche_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributaire',
            name='telephone',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
