# Generated by Django 5.2.9 on 2026-03-31 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches_app', '0006_alter_attributaire_telephone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marche',
            name='statut',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='MarcheValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_history', to='marches_app.marche')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
