# Generated by Django 5.2.9 on 2026-04-27 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marches_app', '0007_alter_marche_statut_marchevalidation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='marche',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marches_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marche',
            name='mode_selection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marche',
            name='type_marche',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
